openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/entlogics1111/Movie_db/1.0.0
info:
  description: This is a simple API
  version: "1.0.0"
  title: User API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: admins
    description: Secured Admin-only calls
  - name: developers
    description: Operations available to regular developers
paths:
  /movies:
    get:
      tags:
        - movies
      summary: list all movies
      operationId: get_movies
      parameters:
        -  in: query
           name: rating
           schema :
            type: string
        -  in: query
           name: gross
           schema :
            type: string
        -  in: query
           name: recommended
           schema :
            type: string
        -  in: query
           name: movie_title
           schema :
            type: string
        -  in: query
           name: company_name
           schema :
            type: string
        -  in: query
           name: first_name
           schema :
            type: string
        -  in: query
           name: last_name
           schema :
            type: string
        -  in: query
           name: genre_description
           schema :
            type: string
      responses:
        '200':
          description: succesfully retrieved list of all movies
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/movies'
                    
        '404':
          description: Page not found
              
              
    post:
      tags:
        - movies
      summary: creating a movie
      operationId: create_movie
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                movie_id:
                  type: integer
                  example: 1
                movie_title:
                    type: string
                    example : Drishyam
                movie_poster:
                    type: string
                    format: binary
                    example: "img.png"
                release_date:
                    type : string
                    format: date
                    example : '2021-09-12'
                release_type:
                  type: string
                  example: Standard release
                pg_rating :
                    type: string
                    example : "G"
                runtime:
                    type: integer
                    example: 124
                budget_dollar:
                    type: integer
                    example: 271329
                total_income_dollar:
                    type: integer
                    example: 9497698
                overview:
                    type: string
                    example: Former wrestler Mahavir Singh Phogat and his two wrestler daughters struggle towards glory at the Commonwealth Games in the face of societal oppression
                genre:
                  type: array
                  items:
                    properties:
                      genre_type:
                        type: string
                  example:
                    - Action
                    - Drama
                language:
                  type: array
                  items:
                    properties:
                      language:
                        type: string
                  example:
                    - Hindi
                    - English
                    - Marathi
                company:
                  type: array
                  items:
                    properties:
                      company_name:
                        type: string
                  example:
                    - Walt Disney pictures
                    - Aamir khan productions
                
      responses:
        '201':
          description: succesfully created a movie record

  /movies/{movie_id}:  
    get:
      tags:
        - movies
      summary: getting details of a movie
      operationId: get_movie
      parameters:
        - in: path
          name: movie_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: succesfully retrieved details of a movie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/movie'
    put:
      tags:
      - movies
      summary: updating a movie
      operationId: edit_movie
      parameters:
      - in:  path
        name: movie_id
        required: true
        schema:
          type: integer
      requestBody:
          content:
              application/json:
                schema:
                  type: object
                  properties:
                    movie_title:
                      type: string
                      example : Drishyam
                    movie_poster:
                      type: string
                      format: binary
                      example: img.png
                    release_date:
                      type : string
                      format: date
                      example: '2021-09-12'
                    release_type:
                      type: string
                      example: Simultaneous release
                    pg_rating :
                      type: string
                      example : "G"
                    runtime:
                      type: integer
                      example: 124
                    budget_dollar:
                      type: integer
                      example: 271329
                    total_income_dollar:
                      type: integer
                      example: 9497698
                    overview:
                      type: string
                      example: Former wrestler Mahavir Singh Phogat and his two wrestler daughters struggle towards glory at the Commonwealth Games in the face of societal oppression
                    language:
                          type: array
                          items:
                            properties:
                              language:
                                type: string
                          example:
                            - Hindi
                            - English
                            - Marathi
                       
      responses:
        '204':
          description: succesfully updated movie details
          
          
    delete:
      tags:
        - movies
      summary: deleting a movie
      operationId: delete_movie
      parameters:
        - in: path
          name: movie_id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: movie is deleted
          
          
  /movies/{movie_id}/ratings:
    get:
      tags:
        - movies
      summary: display movie ratings
      operationId: movie_ratings
      parameters:
        - in: path
          name: movie_id
          required: true
          schema:
            type: integer
            
      responses:
        '200':
          description: succesfully retrieved movie ratings
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/movie-ratings'
            
  /movies/{movie_id}/reviews:  
    get:
      tags:
        - movies
      summary: get all reviews for a movie
      operationId: get_movie_review
      parameters:
        - in: path
          name: movie_id
          required: true
          schema:
            type: integer
            
      responses:
        '200':
          description: succesfully retrieved ratings of a movie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/movie-review'
                
  /movies/{movie_id}/cast:
    get:
      tags:
        - movies
      summary: get all cast members of a movie
      operationId: get_movie_cast
      parameters:
        - in: path
          name: movie_id
          required: true
          schema:
            type: integer
            
      responses:
        '200':
          description: succesfully retrieved cast of a movie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/movie-cast'
                
    post:
      tags:
        - movies
      summary: add cast for a movie
      operationId: post_cast_movie
      parameters:
        - in: path
          name: movie_id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                movie_title:
                    type: string
                    example : Dangal
                cast:
                    type: object
                    properties:
                        person_id:
                          type: integer
                          example: 1
                        first_name:
                          type: string
                          example: Aamir
                        last_name:
                          type: string
                          example: Khan
                        remuneration:
                          type: integer
                          example: 300000
                        actor_role:
                          type: string
                          example: HERO
                        character_name:
                          type: string
                          example: Mahavir Singh Phogat
                       
      responses:
        '201':
          description: succesfully posted a cast member for a movie
          
          
    delete:
      tags:
        - movies
      summary: deleting a cast member
      operationId: delete_cast
      parameters:
        - in: path
          name: movie_id
          required: true
          schema:
            type: integer
            format: int64
        - in: query
          name: person_id
          required: true
          schema:
            type: array
            items:
              type: integer
            
      responses:
        "200":
          description: cast member/members are successfully deleted
          
  /movies/{movie_id}/crew:
    post:
      tags:
        - movies
      summary: add crew for a movie
      operationId: post_crew_movie
      parameters:
        - in: path
          name: movie_id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                movie_title:
                    type: string
                    example : The Matrix
                crew:
                    type: object
                    properties:
                        person_id:
                          type: integer
                          example: 8
                        first_name:
                          type: string
                          example: Bill
                        last_name:
                          type: string
                          example: Pope
                        remuneration:
                          type: integer
                          example: 150000
                        crew_role:
                          type: string
                          example: Cinematographer
                      
      responses:
        '201':
          description: succesfully posted a crew member for a movie
          
          
          
    get:
      tags:
        - movies
      summary: get all crew members of a movie
      operationId: get_movie_crew
      parameters:
        - in: path
          name: movie_id
          required: true
          schema:
            type: integer
            
      responses:
        '200':
          description: succesfully retrieved cast of a movie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/movie-crew'
    delete:
      tags:
        - movies
      summary: deleting a crew member
      operationId: delete_crew
      parameters:
        - in: path
          name: movie_id
          required: true
          schema:
            type: integer
            format: int64
        - in: query
          name: person_id
          required: true
          schema:
            type: array
            items:
              type: integer
            
      responses:
        "200":
          description: crew member/members are successfully deleted
  
  

components: 
        schemas:
                movies :
                    type: array
                    items:
                      properties:
                        movie_id:
                          type: integer
                          example: 1
                        movie_title:
                          type: string
                          example : Drishyam
                        movie_poster:
                          type: string
                          format: binary
                          example: "img.png"
                        release_date:
                          type : string
                          format: date
                          example : 2021-09-12
                        release_type:
                          type: string
                          example: Simultaneous release
                        pg_rating :
                          type: string
                          example : "G"
                        runtime:
                          type: integer
                          example: 124
                        budget_dollar:
                          type: integer
                          example: 271329
                        total_income_dollar:
                          type: integer
                          example: 9497698
                        overall_rating:
                          type: integer
                          format: float
                          example: 7.5
                        no_of_recommendations:
                          type: integer
                          example: 4
                        overview:
                          type: string
                          example: Former wrestler Mahavir Singh Phogat and his two wrestler daughters struggle towards glory at the Commonwealth Games in the face of societal oppression
                        genre:
                          type: array
                          items:
                            properties:
                              name:
                                type: string
                          example:
                            - Action
                            - Drama
                        language:
                          type: array
                          items:
                            properties:
                              language:
                                type: string
                          example:
                            - Hindi
                            - English
                            - Marathi
                        company:
                          type: array
                          items:
                            properties:
                              company_name:
                                type: string
                          example:
                            - Walt Disney pictures
                            - Aamir khan productions
                          
                    
                movie:
                  type: array
                  items:
                      properties:
                        movie_id:
                          type: integer
                          example: 1
                        movie_title:
                          type: string
                          example : Drishyam
                        movie_poster:
                          type: string
                          format: binary
                          example: "img.png"
                        release_date:
                          type : string
                          format: date
                          example : 2021-09-12
                        release_type:
                          type: string
                          example: Standard release
                        pg_rating :
                          type: string
                          example : "G"
                        runtime:
                          type: integer
                          example: 124
                        budget_dollar:
                          type: integer
                          example: 271329
                        total_income_dollar:
                          type: integer
                          example: 9497698
                        overall_rating:
                          type: integer
                          format: float
                          example: 7.5
                        no_of_recommendations:
                          type: integer
                          example: 4
                        overview:
                          type: string
                          example: Former wrestler Mahavir Singh Phogat and his two wrestler daughters struggle towards glory at the Commonwealth Games in the face of societal oppression
                        genre:
                          type: array
                          items:
                            properties:
                              genre_id:
                                type: integer
                              name:
                                type: string
                          example:
                            - genre_id: 1
                              name: Action
                            - genre_id: 2
                              name: Thriller
                        language:
                          type: array
                          items:
                            properties:
                              language_id:
                                type: integer
                              language:
                                type: string
                          example:
                            - language_id: 1 
                              language: Hindi
                            - language_id: 2   
                              language: English
                            - language_id: 3
                              language: Marathi
                        company:
                          type: array
                          items:
                            properties: 
                              company_id:
                                type: integer
                              company_name:
                                type: string
                          example:
                            - company_id: 2
                              company_name: Walt disney pictures
                            - company_id: 34
                              company_name: Aamir khan productions
                            
                movie-review:
                      type: object
                      properties:
                        movie_id:
                          type: integer
                          example : 1
                        movie_title:
                          type: string
                          example: "Mission Impossible:Fallout"
                        Reviews:
                          type: array
                          items:
                            properties:
                              user_id:
                                type: integer
                              username:
                                type: string
                              review:
                                type: string
                              review_added_date:
                                type: string
                                format: date
                          example:
                            - userid: 11
                              username: shivam11
                              review: Total action packed movie, overall a great watch !
                              review_added_date: '2021-05-02'
                            - userid: 22
                              username: baba22
                              review: Great storyline !
                              review_added_date: '2021-05-04'
                            - userid: 33
                              username: cugs33
                              review: A must watch !
                              review_added_date: '2021-05-11'
                            - userid: 44
                              username: redcolie44
                              review: Well directed !
                              review_added_date: '2021-05-23'
                              
                movie-ratings:
                      type: object
                      properties:
                        movie_id:
                          type: integer
                          example : 1
                        movie_title:
                          type: string
                          example: The Matrix
                        Ratings:
                          type: array
                          items:
                            properties:
                              user_id:
                                type: integer
                              rating:
                                type: number
                                format: float 
                              rating_given_date:
                                type: string
                                format: date
                          example:
                            - user_id: 1
                              rating: 7.8
                              rating_given_date: '2021-08-12'
                            - user_id: 2
                              rating: 8.3
                              rating_given_date: '2021-08-13'
                            - user_id: 40
                              rating: 7.1
                              rating_given_date: '2021-08-14'
                            - user_id: 31
                              rating: 8.4
                              rating_given_date: '2021-08-15'
                            - user_id: 150
                              rating: 8.1
                              rating_given_date: '2021-08-16'
                
                movie-cast :
                      type: object
                      properties:
                        movie_id:
                          type: integer
                          example : 1
                        movie_title:
                          type: string
                          example: Shutter Island
                        cast:
                          type: array
                          items:
                            properties:
                              person_id:
                                type: integer
                              first_name:
                                type: string
                              last_name:
                                type: string
                              renumeration:
                                type: number
                              actor_role:
                                type: string
                              character_role:
                                type: string
                          example:
                            - person_id: 1
                              first_name: Leonardo
                              last_name: Di Caprio
                              remuneration: 650000
                              actor_role: Hero
                              character_role: Teddy Daniels
                            - person_id: 45
                              first_name: Mark
                              last_name: Ruffalo
                              remuneration: 560000
                              actor_role: supporting
                              character_role: Chuck Aule
                            - person_id: 28
                              first_name: Ben
                              last_name: Kingsley
                              remuneration: 432000
                              actor_role: Villain
                              character_role: Dr. John Cawley
                            - person_id: 1
                              first_name: Patricia
                              last_name: Clarkson
                              remuneration: 380000
                              actor_role: Heroine
                              character_role: Rachel Solando
                              
                              
                movie-crew:
                  type: object
                  properties:
                        movie_title:
                          type: string
                          example: The matrix
                        crew:
                          type: array
                          items:
                            properties:
                              person_id:
                                type: integer
                              first_name:
                                type: string
                              last_name:
                                type: string
                              remuneration:
                                type: number
                              crew_role:
                                type: string
                          example:
                            - person_id: 6
                              first_name: Bill
                              last_name: Pope
                              remuneration: 15000
                              crew_role: Cinematographer
                            - person_id: 7
                              first_name: Don
                              last_name: Davis
                              remuneration: 88000
                              crew_role: Music director
                            - person_id: 120
                              first_name: Lana
                              last_name: Wachowski
                              remuneration: 120000
                              crew_role: Producer
                              
                                
                                